#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend 6984_frontend
    bind *:80
    default_backend 6984_backend

backend 6984_backend
    balance roundrobin
    server 6984-web-01 18.233.155.106:80 check
    server 6984-web-02 52.91.168.56:80 check
EOF

sudo service haproxy restart