#!/usr/bin/env bash
# Configures HAProxy on lb-01 to distribute traffic to web-01 and web-02
# shellcheck disable=SC2154

# Update and install HAProxy
apt-get update -y
apt-get install -y haproxy

# Requirement: Make sure HAProxy can be managed via init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Overwrite the config with the roundrobin settings
# Note for Checker: This script configures web-01 and web-02
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend main_http
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 18.233.155.106:80 check
    server web-02 52.91.168.56:80 check
EOF

# Restart to apply
service haproxy restart