#!/usr/bin/env bash
# Install nginx and configure a 301 redirect

sudo apt-get -y update
sudo apt-get -y install nginx

# Replace the default location block with a redirect using sed
sudo sed -i '/location \/ {/a\
	location /redirect_me {\
		return 301 https://www.youtube.com/watch;\
	}\
' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart